config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # welcome page
  root 'characters#index'
  # CSV import
  get "/CSVImport/", :to => "csv_import#index"
  post "/CSVImport/importCharacter", :to => "csv_import#importCharacter"
  post "/CSVImport/importFeature", :to => "csv_import#importFeature"

  # for API
  namespace :api do
    namespace :v1 do
      namespace :features do
        get "/get" , :action => "get"
        get "/getMaxUpdate" , :action => "getMaxUpdate"
      end
      namespace :characters do
        get "/get" , :action => "get"
        get "/getMaxUpdate" , :action => "getMaxUpdate"
      end
    end
  end

end

app/models/character.rb
class Character < ApplicationRecord

   def import(characters)
   
   end

end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < ApplicationController
  def get
    if !params[:fromUpdate].blank? then
      @characters = Character.where("to_date(up_date, 'YYYYMMDD') >= to_date(?, 'YYYYMMDD')", params[:fromUpdate])
    else
      @characters = Character.all
    end
    @characters = @characters.map do |character|
      {
        No: character.id,
        PageNo: character.PageNo,
        type: character.characterType,
        name: character.name,
        replaceName: character.replaceName,
        image_name: character.image_name,
        firstScore: character.firstScore,
        upScore: character.upScore,
        maxScore: character.maxScore,
        SL1: character.SL1,
        SL2: character.SL2,
        SL3: character.SL3,
        SL4: character.SL4,
        SL5: character.SL5,
        SL6: character.SL6,
        SLFull: character.SLFull,
        skillDetail: character.skillDetail,
        mustNumChangeFlg: character.mustNumChangeFlg,
        mustNum1: character.mustNum1,
        mustNum2: character.mustNum2,
        mustNum3: character.mustNum3,
        mustNum4: character.mustNum4,
        mustNum5: character.mustNum5,
        mustNum6: character.mustNum6,
        up_date: character.up_date
      }
    end
    render json: @characters
  end

  def getMaxUpdate
    @maxUpdateOfCharacter = Character.maximum('up_date')
    render json: @maxUpdateOfCharacter
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:id, :PageNo, :characterType, :name, :replaceName, :image_name, :firstScore, :upScore, :maxScore, :SL1, :SL2, :SL3, :SL4, :SL5, :SL6, :SLFull, :skillDetail, :mustNumChangeFlg, :mustNum1, :mustNum2, :mustNum3, :mustNum4, :mustNum5, :mustNum6, :up_date)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :No %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :PageNo %>
    <%= form.number_field :PageNo %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :characterType %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :replaceName %>
    <%= form.text_field :replaceName %>
  </div>

  <div class="field">
    <%= form.label :image_name %>
    <%= form.text_field :image_name %>
  </div>

  <div class="field">
    <%= form.label :firstScore %>
    <%= form.number_field :firstScore %>
  </div>

  <div class="field">
    <%= form.label :upScore %>
    <%= form.number_field :upScore %>
  </div>

  <div class="field">
    <%= form.label :maxScore %>
    <%= form.number_field :maxScore %>
  </div>

  <div class="field">
    <%= form.label :SL1 %>
    <%= form.number_field :SL1 %>
  </div>

  <div class="field">
    <%= form.label :SL2 %>
    <%= form.number_field :SL2 %>
  </div>

  <div class="field">
    <%= form.label :SL3 %>
    <%= form.number_field :SL3 %>
  </div>

  <div class="field">
    <%= form.label :SL4 %>
    <%= form.number_field :SL4 %>
  </div>

  <div class="field">
    <%= form.label :SL5 %>
    <%= form.number_field :SL5 %>
  </div>

  <div class="field">
    <%= form.label :SL6 %>
    <%= form.number_field :SL6 %>
  </div>

  <div class="field">
    <%= form.label :SLFull %>
    <%= form.number_field :SLFull %>
  </div>

  <div class="field">
    <%= form.label :skillDetail %>
    <%= form.text_field :skillDetail %>
  </div>

  <div class="field">
    <%= form.label :mustNumChangeFlg %>
    <%= form.check_box :mustNumChangeFlg %>
  </div>

  <div class="field">
    <%= form.label :mustNum1 %>
    <%= form.number_field :mustNum1 %>
  </div>

  <div class="field">
    <%= form.label :mustNum2 %>
    <%= form.number_field :mustNum2 %>
  </div>

  <div class="field">
    <%= form.label :mustNum3 %>
    <%= form.number_field :mustNum3 %>
  </div>

  <div class="field">
    <%= form.label :mustNum4 %>
    <%= form.number_field :mustNum4 %>
  </div>

  <div class="field">
    <%= form.label :mustNum5 %>
    <%= form.number_field :mustNum5 %>
  </div>

  <div class="field">
    <%= form.label :mustNum6 %>
    <%= form.number_field :mustNum6 %>
  </div>

  <div class="field">
    <%= form.label :up_date %>
    <%= form.text_field :up_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h5><a href="/features">to Fetures</a></h5>

<h1>Characters</h1>

<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to 'New Character', new_character_path, class: 'btn btn-success btn-md', style: 'color: white;' %>
    <%= link_to 'CSV Import', '/CSVImport', class: 'btn btn-success btn-md', style: 'color: white;' %>
  </div>
</div>

<table class='table'>
  <thead>
    <tr>
      <th>no</th>
      <th>Pageno</th>
      <th>type</th>
      <th>name</th>
      <th>replaceName</th>
      <th>image_ame</th>
      <th>firstScore</th>
      <th>upScore</th>
      <th>maxScore</th>
      <th>SL1</th>
      <th>SL2</th>
      <th>SL3</th>
      <th>SL4</th>
      <th>SL5</th>
      <th>SL6</th>
      <th>SLFull</th>
      <th>skillDetail</th>
      <th>mustNumChangeFlg</th>
      <th>Musnum1</th>
      <th>mustNum2</th>
      <th>mustNum3</th>
      <th>mustNum4</th>
      <th>mustNum5</th>
      <th>mustNum6</th>
      <th>up_date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.id %></td>
        <td><%= character.PageNo %></td>
        <td><%= character.characterType %></td>
        <td><%= character.name %></td>
        <td><%= character.replaceName %></td>
        <td><%= character.image_name %></td>
        <td><%= character.firstScore %></td>
        <td><%= character.upScore %></td>
        <td><%= character.maxScore %></td>
        <td><%= character.SL1 %></td>
        <td><%= character.SL2 %></td>
        <td><%= character.SL3 %></td>
        <td><%= character.SL4 %></td>
        <td><%= character.SL5 %></td>
        <td><%= character.SL6 %></td>
        <td><%= character.SLFull %></td>
        <td><%= character.skillDetail %></td>
        <td><%= character.mustNumChangeFlg %></td>
        <td><%= character.mustNum1 %></td>
        <td><%= character.mustNum2 %></td>
        <td><%= character.mustNum3 %></td>
        <td><%= character.mustNum4 %></td>
        <td><%= character.mustNum5 %></td>
        <td><%= character.mustNum6 %></td>
        <td><%= character.up_date %></td>
        <td>
          <div class="btn-toolbar">
            <div class="btn-group">
              <%= link_to 'Show', character, class: 'btn btn-default btn-sm' %>
              <%= link_to 'Edit', edit_character_path(character), class: 'btn btn-default btn-sm' %>
              <%= link_to 'Destroy', character, class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No:</strong>
  <%= @character.id %>
</p>

<p>
  <strong>PageNo:</strong>
  <%= @character.PageNo %>
</p>

<p>
  <strong>Type:</strong>
  <%= @character.characterType %>
</p>

<p>
  <strong>name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>replaceName:</strong>
  <%= @character.replaceName %>
</p>

<p>
  <strong>image_name:</strong>
  <%= @character.image_name %>
</p>

<p>
  <strong>firstScore:</strong>
  <%= @character.firstScore %>
</p>

<p>
  <strong>upScore:</strong>
  <%= @character.upScore %>
</p>

<p>
  <strong>maxScore:</strong>
  <%= @character.maxScore %>
</p>

<p>
  <strong>SL1:</strong>
  <%= @character.SL1 %>
</p>

<p>
  <strong>SL2:</strong>
  <%= @character.SL2 %>
</p>

<p>
  <strong>SL3:</strong>
  <%= @character.SL3 %>
</p>

<p>
  <strong>SL4:</strong>
  <%= @character.SL4 %>
</p>

<p>
  <strong>SL5:</strong>
  <%= @character.SL5 %>
</p>

<p>
  <strong>SL6:</strong>
  <%= @character.SL6 %>
</p>

<p>
  <strong>SLFull:</strong>
  <%= @character.SLFull %>
</p>

<p>
  <strong>skillDetail:</strong>
  <%= @character.skillDetail %>
</p>

<p>
  <strong>mustNumChangeFlg:</strong>
  <%= @character.mustNumChangeFlg %>
</p>

<p>
  <strong>mustNum1:</strong>
  <%= @character.mustNum1 %>
</p>

<p>
  <strong>mustNum2:</strong>
  <%= @character.mustNum2 %>
</p>

<p>
  <strong>mustNum3:</strong>
  <%= @character.mustNum3 %>
</p>

<p>
  <strong>mustNum4:</strong>
  <%= @character.mustNum4 %>
</p>

<p>
  <strong>mustNum5:</strong>
  <%= @character.mustNum5 %>
</p>

<p>
  <strong>mustNum6:</strong>
  <%= @character.mustNum6 %>
</p>

<p>
  <strong>up_date:</strong>
  <%= @character.up_date %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>