config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # welcome page
  root 'characters#index'
  # CSV import
  get "/CSVImport/", :to => "csv_import#index"
  post "/CSVImport/importCharacter", :to => "csv_import#importCharacter"
  post "/CSVImport/importFeature", :to => "csv_import#importFeature"

  # for API
  namespace :api do
    namespace :v1 do
      namespace :features do
        get "/get" , :action => "get"
        get "/getMaxUpdate" , :action => "getMaxUpdate"
      end
      namespace :characters do
        get "/get" , :action => "get"
        get "/getMaxUpdate" , :action => "getMaxUpdate"
      end
    end
  end

end

app/models/feature.rb
class Feature < ApplicationRecord
end

app/controllers/api/v1/features_controller.rb
class Api::V1::FeaturesController < ApplicationController
  def get
    if !params[:fromUpdate].blank? then
      @features = Feature.where("to_date(up_date, 'YYYYMMDD') >= to_date(?, 'YYYYMMDD')", params[:fromUpdate])
    else
      @features = Feature.all
    end
    @features = @features.map do | feature |
      {
        row: feature.id,
        no: feature.no,
        type: feature.featureType,
        content: feature.content,
        contentSortNo: feature.contentSortNo,
        up_date: feature.up_date,
        deleteFlg: feature.deleteFlg
      }
    end
    render json: @features
  end

  def getMaxUpdate
    @maxUpdateOfFeature = Feature.maximum('up_date')
    render json: @maxUpdateOfFeature
  end

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:no, :featureType, :content, :contentSortNo, :up_date, :deleteFlg)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.erb
<%= form_with(model: feature, local: true) do |form| %>
  <% if feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Row %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :no %>
    <%= form.number_field :no %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :featureType %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :contentSortNo %>
    <%= form.number_field :contentSortNo %>
  </div>

  <div class="field">
    <%= form.label :up_date %>
    <%= form.text_field :up_date %>
  </div>

  <div class="field">
    <%= form.label :deleteFlg %>
    <%= form.check_box :deleteFlg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing Feature</h1>

<%= render 'form', feature: @feature %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<p id="notice"><%= notice %></p>

<h5><a href="/characters">to Characters</a></h5>

<h1>Features</h1>

<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to 'New Feature', new_feature_path, class: 'btn btn-success btn-md', style: 'color: white;' %>
    <%= link_to 'CSV Import', '/CSVImport', class: 'btn btn-success btn-md', style: 'color: white;' %>
  </div>
</div>


<table class='table'>
  <thead>
    <tr>
      <th>row</th>
      <th>no</th>
      <th>type</th>
      <th>content</th>
      <th>contentSortNo</th>
      <th>up_date</th>
      <th>deleteFlg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @features.each do |feature| %>
      <tr>
        <td><%= feature.id %></td>
        <td><%= feature.no %></td>
        <td><%= feature.featureType %></td>
        <td><%= feature.content %></td>
        <td><%= feature.contentSortNo %></td>
        <td><%= feature.up_date %></td>
        <td><%= feature.deleteFlg %></td>
        <td>
          <div class="btn-toolbar">
            <div class="btn-group">
              <%= link_to 'Show', feature, class: 'btn btn-default btn-sm' %>
              <%= link_to 'Edit', edit_feature_path(feature), class: 'btn btn-default btn-sm' %>
              <%= link_to 'Destroy', feature, class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/features/new.html.erb
<h1>New Feature</h1>

<%= render 'form', feature: @feature %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>row:</strong>
  <%= @feature.id %>
</p>

<p>
  <strong>no:</strong>
  <%= @feature.no %>
</p>

<p>
  <strong>type:</strong>
  <%= @feature.featureType %>
</p>

<p>
  <strong>content:</strong>
  <%= @feature.content %>
</p>

<p>
  <strong>contentSortNo:</strong>
  <%= @feature.contentSortNo %>
</p>

<p>
  <strong>up_date:</strong>
  <%= @feature.up_date %>
</p>

<p>
  <strong>deleteFlg:</strong>
  <%= @feature.deleteFlg %>
</p>

<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>